#!/usr/bin/env bash

# Bun
bunInstalled=$(which bun)
if [ -z "$bunInstalled" ]; then
  curl -fsSL https://bun.sh/install | bash
else
  echo "Bun already installed"
fi

# Homebrew
brewInstalled=$(which brew)
if [ -z "$brewInstalled" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "Homebrew already installed"
fi

brew install zoxide eza bat ripgrep fd fzf jq fastfetch tldr
brew install neovim tmux
brew install yabai skhd
brew install fnm pnpm
brew install orbstack yaak
brew install go

brew install --cask ghostty bitwarden brave-browser

brew tap FelixKratz/formulae
brew install sketchybar ical-buddy
brew services start sketchybar

brew tap FelixKratz/formulae
brew install borders

hash -r
