#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

FG_COLOR=0xffffffff
BG_COLOR=0xa03b4252

bar=(
  height=30
  color=0x00000000
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=8
  margin=10
  notch_width=0
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=5
  padding_right=5
  icon.font="JetBrainsMono Nerd Font:Bold:15.0"
  label.font="JetBrainsMono Nerd Font:Bold:12.0"
  icon.color="$FG_COLOR"
  label.color="$FG_COLOR"
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=5
    icon.padding_right=5
    background.color="$BG_COLOR"
    background.corner_radius=2
    background.height=20
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" background.color="$BG_COLOR" background.corner_radius=2 label.padding_left=10 label.padding_right=10 \
           --subscribe front_app front_app_switched

sketchybar --add item clock right \
           --set clock update_freq=60 icon="" script="$PLUGIN_DIR/clock.sh" background.color="$BG_COLOR" background.corner_radius=2 icon.padding_left=10 label.padding_right=10  \

sketchybar --add item my_calendar right \
           --set my_calendar icon="" \
                          update_freq=60 \
                          script="$PLUGIN_DIR/next_event.sh" \
                          click_script="open -a Calendar" \
                          label.max_chars=60 \
                          background.color="$BG_COLOR" background.corner_radius=2 icon.padding_left=10 label.padding_right=10

sketchybar --add item battery right \
           --set battery \
           update_freq=30 \
           script="$PLUGIN_DIR/battery.sh" \
           background.color="$BG_COLOR" background.corner_radius=2 icon.padding_left=10 label.padding_right=10 \
           --subscribe battery power_source_change

sketchybar --add item warp right \
           --set warp update_freq=1 \
           icon.font="JetBrainsMono Nerd Font:Bold:20.0" \
           label.width=0 \
           label.padding_right=10 \
           background.color="$BG_COLOR" \
           background.corner_radius=2 icon.padding_left=10 icon.padding_right=10 \
           script="$PLUGIN_DIR/warp.sh" \
           click_script="$PLUGIN_DIR/warp-click.sh"

sketchybar --add item net_up right \
           --set net_up icon= \
           icon.font="JetBrainsMono Nerd Font:Bold:10.0" \
           label.font="JetBrainsMono Nerd Font:Bold:10.0" \
           icon.highlight_color=0xff8b0a0d \
           y_offset=5 \
           width=0 \
           update_freq=1 \
           script="$PLUGIN_DIR/net.sh" \

sketchybar --add item net_down right \
           --set net_down icon= \
           icon.font="JetBrainsMono Nerd Font:Bold:10.0" \
           label.font="JetBrainsMono Nerd Font:Bold:10.0" \
           icon.highlight_color=0xff8b0a0d \
           y_offset=-5 \
           update_freq=1 \







##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update




