return { -- Highlight, edit, and navigate code
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  dependencies = {
    'windwp/nvim-ts-autotag',
  },
  main = 'nvim-treesitter.configs',
  opts = {
    ensure_installed = {
      'css',
      'csv',
      'diff',
      'dockerfile',
      'gitignore',
      'go',
      'html',
      'javascript',
      'json5',
      'lua',
      'luadoc',
      'make',
      'markdown',
      'markdown_inline',
      'prolog',
      'sql',
      'tmux',
      'tsx',
      'typescript',
      'vimdoc',
      'yaml',
      'query',
    },
    auto_install = true,
    highlight = {
      enable = true,
    },
    indent = { enable = true },
  },
}
